name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Dockerfile,index.html,nginx.conf"
          target: "/home/ubuntu/github-actions-app"

      - name: Deploy application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/github-actions-app

            echo "Stopping old container..."
            docker stop github-actions-app || true

            echo "Removing old container..."
            docker rm github-actions-app || true

            echo "Building Docker image..."
            docker build -t github-actions-app:latest .

            echo "Starting new container..."
            docker run -d \
              --name github-actions-app \
              -p 8080:80 \
              --restart unless-stopped \
              github-actions-app:latest

            echo "Deployment completed!"

            docker ps
